mod cli;
mod defaults;
mod error;
mod exit;
mod model;
mod output;
mod runtime;
mod service;
use clap::{CommandFactory, Parser, error::ErrorKind};
use cli::deprecation::DeprecationContext;
use cli::{CommandCtx, CommandOutcome, RepoRequirement, RootCli};
use error::{MfError, Result};
use exit::ExitCode;
use output::{Payload, render};
use runtime::AppContext;
use std::{
    ffi::OsString,
    io::{self, Write},
    process::ExitCode as ProcessExitCode,
};
fn main() -> ProcessExitCode {
    match run(std::env::args_os().collect(), &mut io::stdout(), &mut io::stderr()) {
        Ok(code) => ProcessExitCode::from(code as u8),
        Err(err) => {
            let _ = writeln!(io::stderr(), "internal error: {err:#}");
            ProcessExitCode::from(1)
        }
    }
}
fn run(args: Vec<OsString>, stdout: &mut dyn Write, stderr: &mut dyn Write) -> Result<ExitCode> {
    if args.len() <= 1 {
        write_command_help(&mut RootCli::command(), stdout)?;
        return Ok(ExitCode::Ok);
    }
    let cli = match RootCli::try_parse_from(&args) {
        Ok(cli) => cli,
        Err(err) => return handle_parse_error(err, &args, stdout, stderr),
    };
    if cli.global.generate_manual {
        write!(stdout, "<!-- Generated by `mf --generate-manual`; do not edit directly. -->\n\n")?;
        write!(stdout, "{}", clap_markdown::help_markdown_command(&RootCli::command()))?;
        return Ok(ExitCode::Ok);
    }
    let context = match AppContext::from_global_opts(&cli.global) {
        Ok(context) => context,
        Err(err) => {
            render(stderr, cli.global.format, !cli.global.no_color, Payload::Error(&err))?;
            return Ok(err.exit_code());
        }
    };
    tracing::debug!(config_path = %context.config_path().display(), "resolved config path");
    if cli.requires_repo() == RepoRequirement::Required
        && let Err(err) = context.require_repo()
    {
        render(stderr, context.format(), context.color(), Payload::Error(&err))?;
        return Ok(err.exit_code());
    }
    let mut deprecation = DeprecationContext::new(stderr, !context.color());

    let mut cmd_ctx = CommandCtx::new(&context, &mut deprecation);
    let outcome = match cli.dispatch(&mut cmd_ctx) {
        Ok(o) => o,
        Err(err) => {
            render(stderr, context.format(), context.color(), Payload::Error(&err))?;
            return Ok(err.exit_code());
        }
    };
    render_outcome(outcome, &context, stdout, stderr)
}
fn handle_parse_error(
    err: clap::Error,
    args: &[OsString],
    stdout: &mut dyn Write,
    stderr: &mut dyn Write,
) -> Result<ExitCode> {
    match err.kind() {
        ErrorKind::DisplayHelp | ErrorKind::DisplayVersion => {
            write!(stdout, "{err}")?;
            Ok(ExitCode::Ok)
        }
        ErrorKind::InvalidValue if build_output_flag_confusion(&err, args) => {
            // Spec 075 US7/FR-037: `--output <FORMAT>` (text/json) and
            // `mf build`'s `--out <PATH>` are easy to confuse by name; clap's
            // stock enum-validation error lists the valid formats but never
            // mentions that `--out` is the flag that accepts a path.
            let message = err.to_string().trim().trim_start_matches("error:").trim().to_string();
            let mf_error = MfError::usage(message, Some("to set the build output path, use --out instead".to_string()));
            if wants_json_output(args) {
                render(stderr, output::Format::Json, true, Payload::Error(&mf_error))?;
            } else {
                render(stderr, output::Format::Text, true, Payload::Error(&mf_error))?;
            }
            Ok(ExitCode::UsageError)
        }
        _ => {
            if wants_json_output(args) {
                let mf_error = MfError::usage(err.to_string().trim().to_string(), None);
                render(stderr, output::Format::Json, true, Payload::Error(&mf_error))?;
            } else {
                err.print()?;
            }
            Ok(ExitCode::UsageError)
        }
    }
}

/// Best-effort detection of the `--output <FORMAT>` / `mf build --out <PATH>`
/// naming confusion: the failing flag is the global `--output` (not `--out`),
/// and the invocation is `mf build ...`. Clap's error text is the only signal
/// available here since parsing never completed.
fn build_output_flag_confusion(err: &clap::Error, args: &[OsString]) -> bool {
    let is_build = args.iter().any(|a| a.to_str() == Some("build"));
    let is_output_flag = err.to_string().contains("--output <FORMAT>");
    is_build && is_output_flag
}
/// Best-effort scan of raw args to decide whether a parse error should still be
/// emitted as a JSON envelope. Clap never parsed these args, so we recognize every
/// accepted form of the JSON selector: `--json`, and `--output`/`-o` set to `json`
/// (space, `=`, and the short attached `-ojson` forms).
fn wants_json_output(args: &[OsString]) -> bool {
    let mut prev_is_output_flag = false;
    for arg in args {
        let Some(arg) = arg.to_str() else {
            prev_is_output_flag = false;
            continue;
        };
        if arg == "--json" {
            return true;
        }
        if prev_is_output_flag && arg == "json" {
            return true;
        }
        if matches!(arg, "--output=json" | "-o=json" | "-ojson") {
            return true;
        }
        prev_is_output_flag = arg == "--output" || arg == "-o";
    }
    false
}

fn render_outcome(
    outcome: CommandOutcome,
    context: &AppContext,
    stdout: &mut dyn Write,
    stderr: &mut dyn Write,
) -> Result<ExitCode> {
    match outcome {
        CommandOutcome::RootHelp => {
            write_command_help(&mut RootCli::command(), stdout)?;
            Ok(ExitCode::Ok)
        }
        CommandOutcome::GroupHelp(name) => {
            let mut command = RootCli::command();
            let subcommand = command.find_subcommand_mut(name).expect("known subcommand");
            write_command_help(subcommand, stdout)?;
            Ok(ExitCode::Ok)
        }
        CommandOutcome::Completion(shell) => cli::completion::render_completion(shell, stdout),
        CommandOutcome::Success(data, warnings, exit_code) => {
            for warning in &warnings {
                writeln!(stderr, "warning: {warning}")?;
            }
            if context.quiet() {
                return Ok(ExitCode::from(exit_code.unwrap_or(0)));
            }
            let data = inject_warnings(data, &warnings);
            render(stdout, context.format(), context.color(), Payload::Success(&data))?;
            Ok(ExitCode::from(exit_code.unwrap_or(0)))
        }
        CommandOutcome::Raw(content, exit_code) => {
            if context.quiet() {
                return Ok(ExitCode::from(exit_code.unwrap_or(0)));
            }
            render(stdout, context.format(), context.color(), Payload::Raw(content.as_str()))?;
            Ok(ExitCode::from(exit_code.unwrap_or(0)))
        }
    }
    .or_else(|err| {
        let code = err.exit_code();
        render(stderr, context.format(), context.color(), Payload::Error(&err))?;
        Ok(code)
    })
}
/// Inject collected warnings into the JSON data payload when non-empty.
fn inject_warnings(mut data: serde_json::Value, warnings: &[String]) -> serde_json::Value {
    if !warnings.is_empty()
        && let serde_json::Value::Object(ref mut map) = data
    {
        map.insert("warnings".to_string(), serde_json::json!(warnings));
    }
    data
}

fn write_command_help(command: &mut clap::Command, stdout: &mut dyn Write) -> Result<()> {
    let mut buffer = Vec::new();
    command.write_long_help(&mut buffer)?;
    stdout.write_all(&buffer)?;
    Ok(writeln!(stdout)?)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_manual_renders_the_clap_command_tree_without_repo_context() {
        let mut stdout = Vec::new();
        let mut stderr = Vec::new();

        run(vec![OsString::from("mf"), OsString::from("--generate-manual")], &mut stdout, &mut stderr).unwrap();

        let manual = String::from_utf8(stdout).unwrap();
        assert!(manual.starts_with("<!-- Generated by `mf --generate-manual`"));
        assert!(manual.contains("# Command-Line Help for `mf`"));
        assert!(manual.contains("mf build"));
        assert!(stderr.is_empty());
    }
}
